
tasks:
  - name: npm
    init: npm install # runs during prebuild
    command: npm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - vtrois.gitmoji-vscode
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - eamodio.gitlens
    - coenraads.bracket-pair-colorizer-2
    - dbaeumer.vscode-eslint
    - pflannery.vscode-versionlens

gitConfig:
  alias.co: checkout
  alias.br: branch
  alias.ci: commit
  alias.st: status
  pull.rebase: merges
