extends:
  - "stylelint-config-standard"
  - "stylelint-config-html"
# rules:
#  at-rule-no-unknown:
#    - true
#    - ignoreAtRules:
#        - "tailwind"
#        - "apply"
#        - "variants"
#        - "responsive"
#        - "screen"
#  declaration-block-trailing-semicolon: null
#  no-descending-specificity: null
