apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: opensource
spec:
  environments:
    - name: dev
      build:
        from: master
    - name: prod
  components:
    - name: web
      publicPort: http
      ports:
        - name: http
          port: 80
  dnsAppAlias:
    environment: prod
    component: web
  dnsExternalAlias:
    - alias: opensource.equinor.com
      environment: prod
      component: web
